export const GET_RESTAURANTS_REQUEST = "GET_RESTAURANTS_REQUEST";
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAILED = "GET_RESTAURANTS_FAILED";

export const GET_VISITS_REQUEST = "GET_VISITS_REQUEST";
export const GET_VISITS_SUCCESS = "GET_VISITS_SUCCESS";
export const GET_VISITS_FAILED = "GET_VISITS_FAILED";

export const SAVE_VISIT_REQUEST = "SAVE_VISIT_REQUEST";
export const SAVE_VISIT_SUCCESS = "SAVE_VISIT_SUCCESS";
export const SAVE_VISIT_FAILED = "SAVE_VISIT_FAILED";